import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

/// Offline coordinate -> ISO 3166-1 alpha-2 lookup.
///
/// Reads assets/geo/country_borders.json (generated by tools/gen_country_borders.py:
/// Natural Earth 10m, Douglas-Peucker eps 0.002 deg, coordinates as ints scaled by
/// 1000 and delta encoded, all rings of a country tested with one even-odd counter
/// so interior holes such as Lesotho inside South Africa work).
///
/// The asset is 2.6 MB, so parsing happens in a background isolate and the parsed
/// structure is deliberately never retained: only the raw bytes are cached, and
/// each lookup re-parses inside the isolate and returns just the country code.
/// Lookups are rare (a location fix at most), the heap cost is not worth it.
class Borders {
  Borders._();

  static const String _assetPath = 'assets/geo/country_borders.json';
  static const int _cacheLimit = 32;

  static Uint8List? _bytes;
  static final Map<String, String?> _resultCache = <String, String?>{};

  /// Returns the alpha-2 code containing the point, or null over international
  /// waters / unmapped territory.
  static Future<String?> countryAt(double latitude, double longitude) async {
    final String key = '${latitude.toStringAsFixed(3)},'
        '${longitude.toStringAsFixed(3)}';
    if (_resultCache.containsKey(key)) return _resultCache[key];

    Uint8List? bytes = _bytes;
    if (bytes == null) {
      final ByteData data = await rootBundle.load(_assetPath);
      bytes = _bytes =
          data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
    }

    final String? iso = await compute<List<Object>, String?>(
      _lookupInIsolate,
      <Object>[bytes, latitude, longitude],
    );

    if (_resultCache.length >= _cacheLimit) {
      _resultCache.remove(_resultCache.keys.first);
    }
    _resultCache[key] = iso;
    return iso;
  }

  /// Frees the cached asset bytes. Called when the app goes to the background.
  static void releaseMemory() {
    _bytes = null;
    _resultCache.clear();
  }
}

String? _lookupInIsolate(List<Object> args) {
  final Uint8List bytes = args[0] as Uint8List;
  final double lat = args[1] as double;
  final double lon = args[2] as double;

  final Map<String, Object?> root =
      json.decode(utf8.decode(bytes)) as Map<String, Object?>;
  final num scale = (root['scale'] as num?) ?? 1000;
  final double x = lon * scale;
  final double y = lat * scale;

  // Schema 2: overseas territories (Bonaire, Mayotte, Réunion...) that Natural
  // Earth admin-0 folds into their parent live in `subunits` and must be tested
  // FIRST, otherwise a phone in Bonaire is told the Netherlands' 112 instead of
  // its own 911. Precedence is explicit here, never inferred from array order.
  final List<Object?> subunits =
      (root['subunits'] as List<Object?>?) ?? const <Object?>[];
  final List<Object?> countries = root['countries'] as List<Object?>;

  return _firstHit(subunits, x, y) ?? _firstHit(countries, x, y);
}

String? _firstHit(List<Object?> entries, double x, double y) {
  for (final Object? entry in entries) {
    final Map<Object?, Object?> c = entry as Map<Object?, Object?>;
    final List<Object?> bbox = c['b'] as List<Object?>;
    final num minLon = bbox[0] as num;
    final num minLat = bbox[1] as num;
    final num maxLon = bbox[2] as num;
    final num maxLat = bbox[3] as num;
    if (x < minLon || x > maxLon || y < minLat || y > maxLat) continue;

    if (_containsPoint(c['r'] as List<Object?>, x, y)) {
      return (c['c'] as String).toUpperCase();
    }
  }
  return null;
}

/// Even-odd ray cast across every ring of one country, decoding deltas inline.
bool _containsPoint(List<Object?> rings, double x, double y) {
  bool inside = false;

  for (final Object? ringRaw in rings) {
    final List<Object?> ring = ringRaw as List<Object?>;
    final int len = ring.length;
    if (len < 6) continue; // fewer than 3 points

    // First pass is unavoidable: deltas mean we cannot random-access points,
    // and the ray cast needs each edge's two endpoints, so walk it once while
    // keeping the previous point and the ring's first point for the closing edge.
    final double firstX = (ring[0] as num).toDouble();
    final double firstY = (ring[1] as num).toDouble();
    double prevX = firstX;
    double prevY = firstY;

    for (int i = 2; i < len; i += 2) {
      final double curX = prevX + (ring[i] as num).toDouble();
      final double curY = prevY + (ring[i + 1] as num).toDouble();
      if (_crosses(x, y, prevX, prevY, curX, curY)) inside = !inside;
      prevX = curX;
      prevY = curY;
    }
    // Rings are stored implicitly closed.
    if (_crosses(x, y, prevX, prevY, firstX, firstY)) inside = !inside;
  }

  return inside;
}

bool _crosses(
  double x,
  double y,
  double ax,
  double ay,
  double bx,
  double by,
) {
  if ((ay > y) == (by > y)) return false;
  return x < (bx - ax) * (y - ay) / (by - ay) + ax;
}
