import 'dart:convert';

import 'package:flutter/services.dart';

/// One country's emergency numbers, as bundled in
/// assets/data/emergency_numbers.json (generated by tools/gen_emergency_numbers.py).
class CountryNumbers {
  const CountryNumbers({
    required this.iso,
    required this.name,
    required this.general,
    required this.police,
    required this.ambulance,
    required this.fire,
    required this.notes,
  });

  factory CountryNumbers.fromJson(Map<String, Object?> j) => CountryNumbers(
        iso: (j['iso'] as String).toUpperCase(),
        name: j['name'] as String,
        general: _num(j['general']),
        police: _num(j['police']),
        ambulance: _num(j['ambulance']),
        fire: _num(j['fire']),
        notes: (j['notes'] as String?) ?? '',
      );

  final String iso;
  final String name;
  final String? general;
  final String? police;
  final String? ambulance;
  final String? fire;
  final String notes;

  /// The number to put on the big button: a universal one if the country has
  /// one, otherwise police, which is the most widely useful single fallback.
  String? get primary => general ?? police ?? ambulance ?? fire;

  bool get hasUniversalNumber => general != null;

  List<ServiceNumber> get services => <ServiceNumber>[
        if (police != null) ServiceNumber(Service.police, police!),
        if (ambulance != null) ServiceNumber(Service.ambulance, ambulance!),
        if (fire != null) ServiceNumber(Service.fire, fire!),
      ];

  static String? _num(Object? v) {
    if (v is! String) return null;
    final String s = v.trim();
    return s.isEmpty ? null : s;
  }
}

enum Service { general, police, ambulance, fire }

class ServiceNumber {
  const ServiceNumber(this.service, this.number);
  final Service service;
  final String number;
}

/// Loads and holds the bundled dataset. Small enough (~52 KB) to keep in memory.
class NumbersRepository {
  NumbersRepository._(this._byIso, this.generatedUtc, this.source);

  final Map<String, CountryNumbers> _byIso;
  final String generatedUtc;
  final String source;

  static NumbersRepository? _instance;
  static NumbersRepository? get instanceOrNull => _instance;

  static Future<NumbersRepository> load() async {
    final NumbersRepository? cached = _instance;
    if (cached != null) return cached;

    final String raw =
        await rootBundle.loadString('assets/data/emergency_numbers.json');
    final Map<String, Object?> j = json.decode(raw) as Map<String, Object?>;
    final Map<String, Object?> countries =
        (j['countries'] as Map<Object?, Object?>).cast<String, Object?>();

    final Map<String, CountryNumbers> byIso = <String, CountryNumbers>{};
    countries.forEach((String iso, Object? v) {
      byIso[iso.toUpperCase()] =
          CountryNumbers.fromJson((v as Map<Object?, Object?>).cast<String, Object?>());
    });

    return _instance = NumbersRepository._(
      byIso,
      (j['generated_utc'] as String?) ?? '',
      (j['source'] as String?) ?? '',
    );
  }

  int get length => _byIso.length;

  bool has(String? iso) => iso != null && _byIso.containsKey(iso.toUpperCase());

  CountryNumbers? forIso(String? iso) =>
      iso == null ? null : _byIso[iso.toUpperCase()];

  /// All countries, alphabetical by name.
  List<CountryNumbers> get all {
    final List<CountryNumbers> list = _byIso.values.toList(growable: false);
    list.sort((CountryNumbers a, CountryNumbers b) =>
        a.name.toLowerCase().compareTo(b.name.toLowerCase()));
    return list;
  }

  List<CountryNumbers> search(String query) {
    final String q = query.trim().toLowerCase();
    if (q.isEmpty) return all;
    return all
        .where((CountryNumbers c) =>
            c.name.toLowerCase().contains(q) ||
            c.iso.toLowerCase() == q ||
            (c.primary ?? '').startsWith(q))
        .toList(growable: false);
  }
}
