#!/usr/bin/env python3
"""Generate the launcher icons: a white medical cross on Dracula red.

Pure stdlib (zlib only) PNG writer, so the repo needs no image tooling.
Writes the legacy mipmap PNGs and the API 26+ adaptive icon vectors.

    python3 tools/gen_icons.py
"""
from __future__ import annotations

import struct
import zlib
from pathlib import Path

RES = Path(__file__).resolve().parent.parent / "android/app/src/main/res"

RED = (255, 85, 85, 255)        # Dracula red   #FF5555
WHITE = (248, 248, 242, 255)    # Dracula fg    #F8F8F2

DENSITIES = {
    "mipmap-mdpi": 48,
    "mipmap-hdpi": 72,
    "mipmap-xhdpi": 96,
    "mipmap-xxhdpi": 144,
    "mipmap-xxxhdpi": 192,
}


def write_png(path: Path, pixels: list[list[tuple[int, int, int, int]]]) -> None:
    height = len(pixels)
    width = len(pixels[0])
    raw = bytearray()
    for row in pixels:
        raw.append(0)  # filter type 0
        for r, g, b, a in row:
            raw += bytes((r, g, b, a))

    def chunk(tag: bytes, data: bytes) -> bytes:
        return (
            struct.pack(">I", len(data))
            + tag
            + data
            + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)
        )

    png = b"\x89PNG\r\n\x1a\n"
    png += chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0))
    png += chunk(b"IDAT", zlib.compress(bytes(raw), 9))
    png += chunk(b"IEND", b"")
    path.write_bytes(png)


def blend(dst: tuple[int, int, int, int], src: tuple[int, int, int, int], cover: float):
    """Composite src over dst with fractional coverage, for cheap antialiasing."""
    if cover <= 0:
        return dst
    if cover >= 1:
        return src
    return tuple(round(d + (s - d) * cover) for d, s in zip(dst, src))  # type: ignore[return-value]


def icon(size: int) -> list[list[tuple[int, int, int, int]]]:
    """Rounded red square with a white cross, supersampled 3x for smooth edges."""
    ss = 3
    n = size * ss
    radius = n * 0.22
    # Cross geometry as a fraction of the canvas.
    arm = n * 0.62      # total length
    thick = n * 0.215   # bar width
    cx = cy = n / 2.0

    def inside_round_rect(x: float, y: float) -> bool:
        if radius <= 0:
            return True
        left, top, right, bottom = 0.0, 0.0, float(n), float(n)
        nx = min(max(x, left + radius), right - radius)
        ny = min(max(y, top + radius), bottom - radius)
        if nx == x or ny == y:
            return True
        dx, dy = x - nx, y - ny
        return dx * dx + dy * dy <= radius * radius

    def inside_cross(x: float, y: float) -> bool:
        horizontal = abs(x - cx) <= arm / 2 and abs(y - cy) <= thick / 2
        vertical = abs(y - cy) <= arm / 2 and abs(x - cx) <= thick / 2
        return horizontal or vertical

    rows: list[list[tuple[int, int, int, int]]] = []
    for py in range(size):
        row: list[tuple[int, int, int, int]] = []
        for px in range(size):
            hits_bg = 0
            hits_fg = 0
            for sy in range(ss):
                for sx in range(ss):
                    x = px * ss + sx + 0.5
                    y = py * ss + sy + 0.5
                    if inside_round_rect(x, y):
                        hits_bg += 1
                        if inside_cross(x, y):
                            hits_fg += 1
            total = ss * ss
            pixel = blend((0, 0, 0, 0), RED, hits_bg / total)
            pixel = blend(pixel, WHITE, hits_fg / total)
            row.append(pixel)
        rows.append(row)
    return rows


ADAPTIVE_ICON = """<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background"/>
    <foreground android:drawable="@drawable/ic_launcher_foreground"/>
    <monochrome android:drawable="@drawable/ic_launcher_foreground"/>
</adaptive-icon>
"""

BACKGROUND = """<?xml version="1.0" encoding="utf-8"?>
<!-- Dracula red. Generated by tools/gen_icons.py -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path
        android:fillColor="#FF5555"
        android:pathData="M0,0h108v108h-108z"/>
</vector>
"""

# Plus sign centred on (54,54): 44 long arms, 16 thick, well inside the 66dp
# safe zone that launchers may mask down to.
FOREGROUND = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/gen_icons.py -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path
        android:fillColor="#F8F8F2"
        android:pathData="M46,32h16v14h14v16h-14v14h-16v-14h-14v-16h14z"/>
</vector>
"""


def main() -> None:
    for folder, size in DENSITIES.items():
        target = RES / folder
        target.mkdir(parents=True, exist_ok=True)
        path = target / "ic_launcher.png"
        write_png(path, icon(size))
        print(f"{path.relative_to(RES.parent)}  {size}x{size}  {path.stat().st_size} B")

    (RES / "mipmap-anydpi-v26").mkdir(parents=True, exist_ok=True)
    (RES / "mipmap-anydpi-v26/ic_launcher.xml").write_text(ADAPTIVE_ICON)
    (RES / "drawable").mkdir(parents=True, exist_ok=True)
    (RES / "drawable/ic_launcher_background.xml").write_text(BACKGROUND)
    (RES / "drawable/ic_launcher_foreground.xml").write_text(FOREGROUND)
    print("adaptive icon + vectors written")


if __name__ == "__main__":
    main()
